### ISSUE TITLE
db performance

### ISSUE THREAD

**Issue by vitaly-t** [shinuza/sardine#12]
If your database connection parameters do not change, it is a good idea to create `db` instance only once and then reuse it ;)

At the moment you re-create it for each operation.

**Comment by shinuza** [comment]
Hey, I was about to do it but `pgp.end()` triggered my lazy switch. So far you have up to three instances per command (read existing migrations, migration transaction and migration recording) not sure if performance could be an issue right now. But I want to do that at some point but I have to revamp the db code altogether.

**Comment by shinuza** [comment]
Awesome lib by the way, I got spoiled real hard, writing the abstraction layer for the other databases will be a pain in the ass :stuck_out_tongue:

**Comment by vitaly-t** [comment]
Thank you! :)

**Comment by shinuza** [comment]
So this and #13 is all there's left to be done. I think I'll instantiate one db manager per Migrations instance and implement a Migrations#dispose to clean the connections.

**Comment by shinuza** [comment]
Closed by https://github.com/shinuza/sardine/commit/1b156a1c2fefa2f3f325e8345fdf673283d81481
