### ISSUE TITLE
invalid package.json

### ISSUE THREAD

**Issue by vitaly-t** [shinuza/sardine#23]
I think your `package.json` got broken, it misses some of the packages that your code is using, including pg-promise ;)

**Comment by shinuza** [comment]
Hey, didn't get the notification for this. This is fixed. `pg-promise` is no longer used.

See: https://github.com/shinuza/sardine/tree/master/lib/db/drivers

**Comment by vitaly-t** [comment]
Was there an issue with pg-promise that you decided against using it?

**Comment by shinuza** [comment]
Oh no, not at all. I wrote a common interface for drivers as I plan to implement support for mssql, oracle and mysql. I shamelessly stole a lot of your ideas.

**Comment by vitaly-t** [comment]
Ok :) Just note that recent changes in pg-promise addressed issues with nested transactions, in case you are planning to use those, they are awfully complicated.

**Comment by shinuza** [comment]
Oh wow, that's cool. I'll look into that. I owe you a :beer:
